leftnav:
- identifier: db33d21e-2cea-692a-4669-af7caaaf5ee2
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 13a7106e-5229-2b08-58f3-363e43bb14c5
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 8ca7e8b9-9969-75ff-7fc2-970462307455
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 30
- identifier: b82e5929-27a6-e1e3-cfe1-5bf0f39925a8
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 40
- identifier: 52fc88e7-4b46-87f1-bcc4-b78ca2f7d7b6
  name: Video Lectures
  url: /video_galleries/video-lectures
  weight: 50
- identifier: 50a60483-9a10-f753-24a9-31daa158f741
  name: Projects
  url: /pages/projects
  weight: 60
- identifier: 1cc9b5ab-ee17-ef64-c1b0-cec1d832e7a9
  name: Woodpecker Videos
  url: /pages/woodpecker-videos
  weight: 70
- identifier: fe17351d-8f11-4476-31e3-67e3d83ef406
  name: Related Videos
  url: /pages/related-videos
  weight: 80
- identifier: f44fa79a-eca9-fc8f-b2bf-f6acf1da63cd
  name: Faculty Introduction and Background
  parent: 8ca7e8b9-9969-75ff-7fc2-970462307455
  url: /resources/faculty-introduction-and-background
  weight: 10
- identifier: f6bf0ac2-a2f8-3ee9-23e8-0ff20aa472af
  name: Project Examples
  parent: 8ca7e8b9-9969-75ff-7fc2-970462307455
  url: /resources/project-examples
  weight: 20
- identifier: 62f0943d-f5d5-1e8d-5522-a42cca51aad5
  name: Project Logistics and Support
  parent: 8ca7e8b9-9969-75ff-7fc2-970462307455
  url: /resources/project-logistics-and-support
  weight: 30
- identifier: 8256a893-05a0-2cea-5e09-ff9d4d35b5b8
  name: Lecture Preparation
  parent: 8ca7e8b9-9969-75ff-7fc2-970462307455
  url: /resources/lecture-preparation
  weight: 40
- identifier: e87e7f4c-a1cd-a633-9c24-c6195874bcc4
  name: Role of Images in the Course
  parent: 8ca7e8b9-9969-75ff-7fc2-970462307455
  url: /resources/role-of-images-in-the-course
  weight: 50
- identifier: 0e8be639-dad9-67f2-27c9-787df8aa65b9
  name: Unique Aspects of the Course
  parent: 8ca7e8b9-9969-75ff-7fc2-970462307455
  url: /resources/unique-aspects-of-the-course
  weight: 60
